[package]
authors = ["marcelbuesing <buesing.marcel@googlemail.com>"]
description = "A pure Rust implementation for the BME680 environmental sensor."
documentation = "https://docs.rs/bme680"
license = "MIT"
name = "bme680"
repository = "https://github.com/marcelbuesing/bme680-hal"
version = "0.5.1"
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/marcelbuesing/bme680-hal", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
bitflags = "1.2"
embedded-hal = "0.2"
log = "0.4"

[dev-dependencies]
env_logger = "0.7"
futures = { version = "0.3" }
i2cdev = "0.4"
influx_db_client = { version = "0.4", default-features= false, features = ["rustls-tls"] }
linux-embedded-hal = "0.3"
tokio = {version = "0.2", features = ["full"] }
url = "2.1"
